# Generated by Django 2.2.17 on 2021-01-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_customtext_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="customtext",
            name="test_1",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customtext",
            name="test_2",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
