# Generated by Django 2.2.17 on 2021-01-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_auto_20210104_1209"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="demo_ASDF_ASDF_ASDF_ASDF_ASDF_ASDF_SADF_ADSF",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="new_jfi",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="testing",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
